export {
  type Burst,
  bucketIntoBursts,
  type HumanEdit,
  type SessionTransaction,
} from './burst-grouping.ts';
export {
  CLIENT_RUNTIME_VERSION_FALLBACK,
  CLIENT_VERSION_HEADER,
  type ClientKind,
  type ClientVersionInput,
  type ClientVersionTokenFields,
  clientVersionHeaders,
  clientVersionTokenFields,
} from './client-version.ts';
export type {
  BundleManifest,
  BundleRedaction,
  ClassifiedPath,
  Loggable,
  LogLevel,
  LogPayload,
  SerializedError,
  SerializedErrorTruncation,
} from './logger-types.ts';
export { LOG_LEVELS } from './logger-types.ts';
export {
  mapConsoleLevel,
  parseStructuredConsoleMessage,
  RENDERER_LOG_MAX_BATCH_BYTES,
  RENDERER_LOG_MAX_ENTRIES,
  RENDERER_LOG_MAX_MESSAGE_BYTES,
  type RendererLogLevel,
  truncateLogMessage,
} from './logging/renderer-log.ts';
export { PROTOCOL_VERSION } from './protocol-version.ts';


export { VFileMessage } from 'vfile-message';
export {
  bindConfigDoc,
  type ConfigBinding,
  type ConfigBindingPatchResult,
  type ConfigBindingPatchSuccess,
  type ConfigDocProvider,
  type Unsubscribe,
} from './config/bind-config-doc.ts';
export {
  type BindOkignoreDocOptions,
  bindOkignoreDoc,
  type OkignoreBinding,
  type OkignoreBindingPatchResult,
  type OkignoreBindingPatchSuccess,
  type OkignoreBindingRejection,
  type OkignoreBindingStatus,
  type OkignoreDocProvider,
  type OkignoreUnsubscribe,
} from './config/bind-okignore-doc.ts';
export {
  type ConfigIssue,
  ConfigIssueSchema,
  type ConfigIssueSource,
  ConfigIssueSourceSchema,
  type ConfigValidationError,
  ConfigValidationErrorSchema,
  type FieldScope,
  FieldScopeSchema,
  type ForwardCompatConfigError,
  ForwardCompatConfigErrorSchema,
  humanFormat,
  isKnownConfigError,
  type KnownConfigValidationError,
  KnownConfigValidationErrorSchema,
  type WriteScope,
  WriteScopeSchema,
} from './config/errors.ts';
export {
  type FieldMeta,
  fieldRegistry,
  getFieldMeta,
} from './config/field-registry.ts';
export { mergeLayered } from './config/merge-layered.ts';
export {
  type DetectRemovedKeysInput,
  detectRemovedKeys,
  REMOVED_KEYS,
  type RemovedKey,
} from './config/removed-keys.ts';
export type { Err, Ok, Result } from './config/result.ts';
export {
  type Config,
  type ConfigPatch,
  ConfigSchema,
  DEFAULT_EMBEDDINGS_BASE_URL,
  DEFAULT_EMBEDDINGS_MODEL,
  DEFAULT_LOGS_MAX_BYTES,
  DEFAULT_SPANS_MAX_BYTES,
  DEFAULT_TELEMETRY_ATTRIBUTE_DENYLIST,
} from './config/schema.ts';
export { getLeafFieldMeta, resolveLeafSchema } from './config/schema-leaf.ts';
export { CONFIG_SCHEMA_MAJOR, CONFIG_SCHEMA_MAJOR_PATH } from './config/schema-version.ts';
export { type LocateOptions, locateIssue } from './config/source-locator.ts';
export {
  addConfigSpanEvent,
  type ConfigOutcome,
  type ConfigScopeAttr,
  type ConfigSpanAttributes,
  type ConfigTransport,
  type ConfigValidationLayer,
  setConfigOutcome,
  withConfigSpan,
  withConfigSpanSync,
} from './config/telemetry.ts';
export {
  ACTIVITY_TTL_MS,
  evictStaleEntries,
  FLASH_DEBOUNCE_MS,
  FLASH_DURATION_MS,
  hasNewEntries,
} from './constants/activity.ts';
export {
  CC1_CONTRACT_VERSION,
  CONFIG_DOC_NAME_OKIGNORE,
  CONFIG_DOC_NAME_PROJECT,
  CONFIG_DOC_NAME_PROJECT_LOCAL,
  CONFIG_DOC_NAME_USER,
  CONFIG_DOC_NAMES,
  type ConfigDocName,
  SYSTEM_DOC_NAME,
} from './constants/cc1.ts';
export {
  CODE_FILE_BARE_NAMES_TO_LANGUAGE,
  CODE_FILE_EXTENSIONS_TO_LANGUAGE,
  codeLanguageForBareFilename,
  codeLanguageForExtension,
} from './constants/code-languages.ts';
export type { CreateNewBannerKind } from './constants/create-new-banner.ts';
export {
  CREATE_NEW_PROJECT_FAILURE_REASONS,
  type CreateNewProjectFailureReason,
} from './constants/create-new-project-reason.ts';
export {
  DEFAULT_DOC_EXTENSION,
  type DocExtension,
  SUPPORTED_DOC_EXTENSIONS,
} from './constants/doc-extensions.ts';
export { LINEAGE_EPOCH_KEY } from './constants/doc-lifecycle.ts';
export {
  DOCUMENT_OPEN_BYTE_LIMIT,
  isDocumentOverOpenByteLimit,
} from './constants/document-open.ts';
export {
  ALL_EDITOR_IDS,
  EDITOR_LABELS,
  type EditorId,
} from './constants/editors.ts';
export {
  detectEmbeddedHostFromBrowser,
  type EmbeddedHost,
  UA_PATTERNS,
} from './constants/embedded-host.ts';
export { SHOW_INSTALL_SKILL } from './constants/feature-flags.ts';
export type { OkFolderState } from './constants/folder-state.ts';
export { DEFAULT_GITHUB_OAUTH_CLIENT_ID } from './constants/github.ts';
export { isOrphanMode, ORPHAN_MODES, type OrphanMode } from './constants/graph.ts';
export { GREP_MAX_RESULTS, MCP_SERVER_NAME, READ_DOCUMENT_HISTORY_DEPTH } from './constants/mcp.ts';
export { MENU_LABELS, type MenuLabelKey } from './constants/menu-labels.ts';
export { LOCAL_DIR, OK_DIR, OK_PROJECT_MARKER } from './constants/ok-dir.ts';
export {
  PREVIEW_EMBED_STARTERS,
  type PreviewEmbedStarter,
  previewEmbedFence,
} from './constants/preview-embed-starters.ts';
export {
  PREVIEW_THEME_TOKENS,
  type PreviewThemeToken,
} from './constants/preview-theme-tokens.ts';
export { PRODUCT_NAME } from './constants/product.ts';
export { DEFAULT_SERVER_HOST } from './constants/server.ts';
export {
  ALLOWED_AUDIO_MIME_TYPES,
  ALLOWED_IMAGE_MIME_TYPES,
  ALLOWED_PDF_MIME_TYPES,
  ALLOWED_VIDEO_MIME_TYPES,
  ASSET_EXTENSIONS,
  AUDIO_EXTENSIONS,
  CODE_FILE_EXTENSIONS,
  DEFAULT_ATTACHMENT_FOLDER_PATH,
  DEFAULT_DEDUP_MODE,
  DEFAULT_DEDUP_UI,
  DEFAULT_EMIT_FORMAT,
  type DedupMode,
  type DedupUIMode,
  type EmitFormat,
  EXECUTABLE_BLOCKLIST_EXTENSIONS,
  FILE_ATTACHMENT_EXTENSIONS,
  IMAGE_EXTENSIONS,
  INLINE_RENDERABLE_EXTENSIONS,
  type InlineAssetMediaKind,
  LINKABLE_ASSET_EXTENSIONS,
  mediaKindForSidebarAssetExtension,
  PDF_EXTENSIONS,
  SANDBOXED_HTML_CSP,
  SANDBOXED_HTML_EXTENSIONS,
  SIDEBAR_AUDIO_ASSET_EXTENSIONS,
  SIDEBAR_IMAGE_ASSET_EXTENSIONS,
  SIDEBAR_PDF_ASSET_EXTENSIONS,
  SIDEBAR_RENDERABLE_ASSET_EXTENSIONS,
  SIDEBAR_TEXT_ASSET_EXTENSIONS,
  SIDEBAR_VIDEO_ASSET_EXTENSIONS,
  TEXT_VIEWER_FALLBACK_EXTENSIONS,
  VIDEO_EXTENSIONS,
  WIKI_EMBED_EXTENSIONS,
} from './constants/upload.ts';
export { CodeBlockFidelity } from './extensions/code-block-fidelity.ts';
export { EmphasisFidelity, StrongFidelity } from './extensions/emphasis-fidelity.ts';
export { EscapeMark } from './extensions/escape-mark.ts';
export { FootnoteDefinition } from './extensions/footnote-definition.ts';
export {
  collectFootnoteIdentifiers,
  FootnoteReference,
  findFootnoteDefinitionInsertPos,
  nextFootnoteIdentifier,
} from './extensions/footnote-reference.ts';
export {
  FM_FENCE_LINE_RE,
  FRONTMATTER_RE,
  prependFrontmatter,
  stripFrontmatter,
  unwrapFrontmatterFences,
} from './extensions/frontmatter.ts';
export { HardBreakFidelity } from './extensions/hard-break-fidelity.ts';
export { HeadingFidelity } from './extensions/heading-fidelity.ts';
export { HtmlBlockFidelity } from './extensions/html-block-fidelity.ts';
export { ImageSrcFidelity } from './extensions/image-src-fidelity.ts';
export { JsxComponent } from './extensions/jsx-component.ts';
export { JsxInline } from './extensions/jsx-inline.ts';
export { LinkFidelity } from './extensions/link-fidelity.ts';
export { LinkRefDefFidelity } from './extensions/link-ref-def-fidelity.ts';
export { List, ListItem, ListItemNode, ListNode } from './extensions/list.ts';
export { MathInline } from './extensions/math-inline.ts';
export { RawMdxFallback } from './extensions/raw-mdx-fallback.ts';
export { sharedExtensions } from './extensions/shared.ts';
export { Tag } from './extensions/tag.ts';
export { ThematicBreakFidelity } from './extensions/thematic-break-fidelity.ts';
export {
  getWikiLinkText,
  normalizeNullableString,
  parseWikiLink,
  renderWikiLink,
  WikiLink,
  type WikiLinkAttrs,
} from './extensions/wiki-link.ts';
export {
  WikiLinkEmbed,
  type WikiLinkEmbedAttrs,
} from './extensions/wiki-link-embed.ts';
export {
  type BridgeWorktreeEntry,
  parseWorktreeListPorcelain,
} from './git/worktree-list-parser.ts';
export {
  type AssembleHandoffPromptInput,
  assembleHandoffPrompt,
  assertNeverUrnIpcLookup,
  buildClaudeLaunchCommand,
  buildClaudeUrl,
  buildCliLaunchCommand,
  buildCodexUrl,
  buildCursorUrl,
  type ComposeSelection,
  type CreateScenario,
  composeAskProjectPrompt,
  composeAskPrompt,
  composeCreatePrompt,
  composeEmptySpacePrompt,
  composeFilePrompt,
  composeFolderPrompt,
  composeSelectionPrompt,
  composeTerminalBareLaunchPrompt,
  type DocContext,
  type HandoffFailureReason,
  type HandoffOutcome,
  type HandoffPayload,
  type HandoffScope,
  type HandoffTarget,
  type InstallState,
  type IpcChannelReason,
  type IpcChannelWithUrn,
  lookupUrnInRegistry,
  OK_PROJECT_SKILL_POINTER,
  OK_TERMINAL_SURFACE_PREAMBLE,
  shellSingleQuote,
  type TargetData,
  TERMINAL_CLI_IDS,
  TERMINAL_CLIS,
  type TerminalCli,
  type TerminalCliInfo,
  URN_HTTP_ONLY,
  URN_IPC_REGISTRY,
  type UrnIpcLookup,
  withSkillPointer,
} from './handoff/index.ts';
export {
  HTML_MAX_BYTES,
  HtmlPayloadTooLargeError,
  htmlToMdast,
  mdastToMarkdown,
} from './markdown/html-to-mdast.ts';
export { MarkdownManager } from './markdown/index.ts';
export { markdownToHtml, mdastToHtml } from './markdown/mdast-to-html.ts';
export { normalizeDocRelativeAssetUrl } from './markdown/resolve-image-url.ts';
export {
  isRelativeUrl,
  isSafeUrl,
  SAFE_URL_SCHEME_RE,
  SAFE_URL_SCHEMES,
} from './markdown/safe-url.ts';
export {
  createTagInTextRegex,
  INLINE_TAG_VALUE_RE,
  TAG_IN_TEXT_PATTERN_SOURCE,
} from './markdown/tag-promotion.ts';
export {
  getParseHealth,
  incrementBlockFallback,
  incrementBlockGripClickSelectFailed,
  incrementJsxArrowNodeSelectFailed,
  incrementJsxAutoConvertFailed,
  incrementJsxAutoConvertSucceeded,
  incrementJsxKeyboardDeleteFailed,
  incrementJsxMoveFailed,
  incrementJsxPopoverCloseRestoreFailed,
  incrementJsxPropDropped,
  incrementJsxRenderFailure,
  incrementJsxStuckCopyFailed,
  incrementJsxStuckDeleteFailed,
  incrementWholeDocFallback,
  incrementYpsMismatchBlock,
  incrementYpsMismatchInline,
  type ParseHealthMetrics,
  resetParseHealth,
} from './metrics/parse-health.ts';
export {
  builtInComponents,
  type ComponentRegistry,
  createRegistry,
  wildcardMeta,
} from './registry/index.ts';
export {
  type ComponentEntryFull,
  type ComponentEntryLite,
  type ComponentKind,
  type ComponentParam,
  getAgentCanonicalDescriptors,
  getCanonicalDescriptors,
  projectFull,
  projectLite,
  renderInventoryFooter,
} from './registry/projection.ts';
export type {
  ClipboardHastContext,
  JsxComponentMeta,
  PropDef,
  PropDefBase,
  PropDefBoolean,
  PropDefEnum,
  PropDefNumber,
  PropDefReactNode,
  PropDefString,
} from './registry/types.ts';
export {
  type ActivityAgentHeader,
  ActivityAgentHeaderSchema,
  type ActivityBurst,
  ActivityBurstSchema,
  type ActivityFile,
  ActivityFileSchema,
  type AdvisoryWarning,
  AdvisoryWarningSchema,
  AdvisoryWarningsSchema,
  type AgentActivitySuccess,
  AgentActivitySuccessSchema,
  type AgentBurstDiffSuccess,
  AgentBurstDiffSuccessSchema,
  type AgentPatchRequest,
  AgentPatchRequestSchema,
  type AgentPatchSuccess,
  AgentPatchSuccessSchema,
  AgentPresenceEntrySchema,
  type AgentPresenceEntryWire,
  type AgentUndoRequest,
  AgentUndoRequestSchema,
  type AgentUndoSuccess,
  AgentUndoSuccessSchema,
  type AgentWriteMdRequest,
  AgentWriteMdRequestSchema,
  type AgentWriteMdSuccess,
  AgentWriteMdSuccessSchema,
  type AgentWriteRequest,
  AgentWriteRequestSchema,
  type AgentWriteSuccess,
  AgentWriteSuccessSchema,
  type ApiConfigSuccess,
  ApiConfigSuccessSchema,
  assertNeverProblemType,
  type BacklinkCountsSuccess,
  BacklinkCountsSuccessSchema,
  type BacklinkEntry,
  BacklinkEntrySchema,
  type BacklinksSuccess,
  BacklinksSuccessSchema,
  type BranchInfoResponse,
  BranchInfoResponseSchema,
  type CheckoutFailureReason,
  CheckoutFailureReasonSchema,
  type CheckoutRequest,
  CheckoutRequestSchema,
  type CheckoutResponse,
  CheckoutResponseSchema,
  type ClassifiedGitAuthError,
  type ClientLogEntry,
  ClientLogEntrySchema,
  type ClientLogsRequest,
  ClientLogsRequestSchema,
  type ClientLogsSuccess,
  ClientLogsSuccessSchema,
  ConflictEntrySchema,
  type ConflictEntryWire,
  type ContentDivergenceCurrentState,
  ContentDivergenceCurrentStateSchema,
  type ContentDivergenceWarning,
  ContentDivergenceWarningSchema,
  type CreateFolderRequest,
  CreateFolderRequestSchema,
  type CreateFolderSuccess,
  CreateFolderSuccessSchema,
  type CreatePageRequest,
  CreatePageRequestSchema,
  type CreatePageSuccess,
  CreatePageSuccessSchema,
  classifyGitAuthError,
  type DeadLinkEntry,
  DeadLinkEntrySchema,
  type DeadLinkSource,
  DeadLinkSourceSchema,
  type DeadLinksSuccess,
  DeadLinksSuccessSchema,
  type DeletePathRequest,
  DeletePathRequestSchema,
  type DeletePathSuccess,
  DeletePathSuccessSchema,
  type DiskEditReconciledWarning,
  DiskEditReconciledWarningSchema,
  type DocumentListEntry,
  DocumentListEntrySchema,
  type DocumentListSuccess,
  DocumentListSuccessSchema,
  type DocumentReadSuccess,
  DocumentReadSuccessSchema,
  type DuplicatePathRequest,
  DuplicatePathRequestSchema,
  type DuplicatePathSuccess,
  DuplicatePathSuccessSchema,
  type EmbedDetection,
  EmbedDetectionSchema,
  type EmbedDetectSuccess,
  EmbedDetectSuccessSchema,
  EmbedProbeEntrySchema,
  type EmbedProbeEntryWire,
  type EmptyRequest,
  EmptyRequestSchema,
  type FolderConfigGetSuccess,
  FolderConfigGetSuccessSchema,
  type FolderConfigPutRequest,
  FolderConfigPutRequestSchema,
  type FolderConfigPutSuccess,
  FolderConfigPutSuccessSchema,
  type ForwardLinkDocEntry,
  ForwardLinkDocEntrySchema,
  type ForwardLinkEntry,
  ForwardLinkEntrySchema,
  type ForwardLinkExternalEntry,
  ForwardLinkExternalEntrySchema,
  type ForwardLinksSuccess,
  ForwardLinksSuccessSchema,
  type FrontmatterPatchRequest,
  FrontmatterPatchRequestSchema,
  type FrontmatterPatchSuccess,
  FrontmatterPatchSuccessSchema,
  type GitAuthFailureSubclass,
  type HeadingEntry as PageHeadingEntry,
  HeadingEntrySchema as PageHeadingEntrySchema,
  type HistoryEntry,
  HistoryEntrySchema,
  type HistoryShadowContributor,
  HistoryShadowContributorSchema,
  type HistorySuccess,
  HistorySuccessSchema,
  type HistoryVersionSuccess,
  HistoryVersionSuccessSchema,
  type HubEntry,
  HubEntrySchema,
  type HubsSuccess,
  HubsSuccessSchema,
  type InstalledAgentsSuccess,
  InstalledAgentsSuccessSchema,
  type InstallSkillRequest,
  InstallSkillRequestSchema,
  type InstallSkillSuccess,
  InstallSkillSuccessSchema,
  isBranchNotFoundGitError,
  isLoginFixableGitAuthError,
  isValidBranchName,
  type LifecycleStatus,
  LifecycleStatusSchema,
  type LinkGraphDocNode,
  LinkGraphDocNodeSchema,
  type LinkGraphEdge,
  LinkGraphEdgeSchema,
  type LinkGraphExternalNode,
  LinkGraphExternalNodeSchema,
  type LinkGraphNode,
  LinkGraphNodeSchema,
  type LinkGraphSuccess,
  LinkGraphSuccessSchema,
  type LocalOpAuthEmptySuccess,
  LocalOpAuthEmptySuccessSchema,
  type LocalOpAuthHostRequest,
  LocalOpAuthHostRequestSchema,
  type LocalOpAuthSetIdentityRequest,
  LocalOpAuthSetIdentityRequestSchema,
  type LocalOpAuthStatusSuccess,
  LocalOpAuthStatusSuccessSchema,
  type LocalOpCloneRequest,
  LocalOpCloneRequestSchema,
  type LocalOpEmbeddingsMutationSuccess,
  LocalOpEmbeddingsMutationSuccessSchema,
  type LocalOpEmbeddingsSetKeyRequest,
  LocalOpEmbeddingsSetKeyRequestSchema,
  type LocalOpOkInitFailureReason,
  LocalOpOkInitFailureReasonSchema,
  type LocalOpOkInitRequest,
  LocalOpOkInitRequestSchema,
  type LocalOpOkInitResponse,
  LocalOpOkInitResponseSchema,
  type MetricsAgentPresenceSuccess,
  MetricsAgentPresenceSuccessSchema,
  type MetricsParseHealthSuccess,
  MetricsParseHealthSuccessSchema,
  type MetricsReconciliationSuccess,
  MetricsReconciliationSuccessSchema,
  type OrphanEntry,
  OrphanEntrySchema,
  type OrphanHint,
  OrphanHintSchema,
  type OrphansSuccess,
  OrphansSuccessSchema,
  type PageEntry,
  PageEntrySchema,
  type PageHeadingsSuccess,
  PageHeadingsSuccessSchema,
  type PagesSuccess,
  PagesSuccessSchema,
  type PrincipalSuccess,
  PrincipalSuccessSchema,
  type ProblemDetails,
  ProblemDetailsSchema,
  type ProblemType,
  ProblemTypeSchema,
  PushPermissionSchema,
  type PushPermissionWire,
  type RenamedAssetMapping,
  RenamedAssetMappingSchema,
  type RenamedDocMapping,
  RenamedDocMappingSchema,
  type RenamePathRequest,
  RenamePathRequestSchema,
  type RenamePathSuccess,
  RenamePathSuccessSchema,
  type RenameRewrittenDoc,
  RenameRewrittenDocSchema,
  type RenderWarning,
  RenderWarningSchema,
  type RescueEntryFlat,
  RescueEntryFlatSchema,
  type RescueEntryTimeline,
  RescueEntryTimelineSchema,
  type RescueListSuccess,
  RescueListSuccessSchema,
  type RollbackRequest,
  RollbackRequestSchema,
  type RollbackSuccess,
  RollbackSuccessSchema,
  type SaveVersionRequest,
  SaveVersionRequestSchema,
  type SaveVersionSuccess,
  SaveVersionSuccessSchema,
  type SaveVersionWriter,
  SaveVersionWriterSchema,
  type SearchRequest,
  SearchRequestSchema,
  type SearchResultEntry,
  SearchResultEntrySchema,
  type SearchSemanticStatus,
  SearchSemanticStatusSchema,
  type SearchSource,
  type SearchSuccess,
  SearchSuccessSchema,
  type SeedApplyRequest,
  SeedApplyRequestSchema,
  type SeedApplySuccess,
  SeedApplySuccessSchema,
  type SeedListPacksSuccess,
  SeedListPacksSuccessSchema,
  type SeedPackEntryCounts,
  SeedPackEntryCountsSchema,
  type SeedPackFolderInfo,
  SeedPackFolderInfoSchema,
  type SeedPackInfo,
  SeedPackInfoSchema,
  type SeedPlanSuccess,
  SeedPlanSuccessSchema,
  type SemanticIndexStatus,
  SemanticIndexStatusSchema,
  type ServerInfoSuccess,
  ServerInfoSuccessSchema,
  type ShareConstructUrlErrorCode,
  ShareConstructUrlErrorCodeSchema,
  type ShareConstructUrlRequest,
  ShareConstructUrlRequestSchema,
  type ShareConstructUrlResponse,
  ShareConstructUrlResponseSchema,
  type SharePublishErrorCode,
  SharePublishErrorCodeSchema,
  type SharePublishNameCheckResponse,
  SharePublishNameCheckResponseSchema,
  type SharePublishOwner,
  type SharePublishOwnerKind,
  SharePublishOwnerKindSchema,
  SharePublishOwnerSchema,
  type SharePublishOwnersErrorCode,
  SharePublishOwnersErrorCodeSchema,
  type SharePublishOwnersResponse,
  SharePublishOwnersResponseSchema,
  type SharePublishRequest,
  SharePublishRequestSchema,
  type SharePublishResponse,
  SharePublishResponseSchema,
  type SharePublishVisibility,
  SharePublishVisibilitySchema,
  type SkillInstallStateSuccess,
  SkillInstallStateSuccessSchema,
  type SkillInstallTargetState,
  SkillInstallTargetStateSchema,
  type SpawnCursorRequest,
  SpawnCursorRequestSchema,
  type SpawnCursorSuccess,
  SpawnCursorSuccessSchema,
  type StreamingProblemEvent,
  StreamingProblemEventSchema,
  type SuggestLinksMention,
  SuggestLinksMentionSchema,
  type SuggestLinksSuccess,
  SuggestLinksSuccessSchema,
  type SuggestLinksTarget,
  SuggestLinksTargetSchema,
  type SummaryResponseField,
  SummaryResponseFieldSchema,
  SYNC_ERROR_CODES,
  type SyncConflictContentSuccess,
  SyncConflictContentSuccessSchema,
  type SyncConflictsSuccess,
  SyncConflictsSuccessSchema,
  type SyncErrorCode,
  SyncErrorCodeSchema,
  SyncRemoteSchema,
  type SyncRemoteWire,
  type SyncResolveConflictRequest,
  SyncResolveConflictRequestSchema,
  type SyncResolveConflictSuccess,
  SyncResolveConflictSuccessSchema,
  SyncStateSchema,
  type SyncStateWire,
  SyncStatusSchema,
  type SyncStatusWire,
  type SyncTriggerRequest,
  SyncTriggerRequestSchema,
  type SyncTriggerSuccess,
  SyncTriggerSuccessSchema,
  type TagSummaryEntry,
  TagSummaryEntrySchema,
  type TagsDocEntry,
  TagsDocEntrySchema,
  type TagsForNameSuccess,
  TagsForNameSuccessSchema,
  type TagsListSuccess,
  TagsListSuccessSchema,
  type TemplateDeleteSuccess,
  TemplateDeleteSuccessSchema,
  type TemplateFrontmatter,
  TemplateFrontmatterSchema,
  type TemplateGetSuccess,
  TemplateGetSuccessSchema,
  type TemplateMoveRequest,
  TemplateMoveRequestSchema,
  type TemplateMoveSuccess,
  TemplateMoveSuccessSchema,
  type TemplatePayload,
  TemplatePayloadSchema,
  type TemplatePutRequest,
  TemplatePutRequestSchema,
  type TemplatePutSuccess,
  TemplatePutSuccessSchema,
  type TemplatesListEntry,
  TemplatesListEntrySchema,
  type TemplatesListSuccess,
  TemplatesListSuccessSchema,
  type TestFlushGitSuccess,
  TestFlushGitSuccessSchema,
  type TestRescanBacklinksSuccess,
  TestRescanBacklinksSuccessSchema,
  type TestRescanFilesSuccess,
  TestRescanFilesSuccessSchema,
  type TestResetSuccess,
  TestResetSuccessSchema,
  type TrashCleanupRequest,
  TrashCleanupRequestSchema,
  type TrashCleanupSuccess,
  TrashCleanupSuccessSchema,
  type UploadAssetSuccess,
  UploadAssetSuccessSchema,
  type UploadRequest,
  UploadRequestSchema,
  type WorkspaceSuccess,
  WorkspaceSuccessSchema,
  type WriteWarning,
  WriteWarningSchema,
} from './schemas/api/index.ts';
export {
  CC1_CHANNEL_BRANCH_SWITCHED,
  CC1_CHANNEL_CONFIG_IGNORE_NESTED_ERROR,
  CC1_CHANNEL_CONFIG_VALIDATION_REJECTED,
  CC1_CHANNEL_DISK_ACK,
  CC1_CHANNEL_SERVER_INFO,
  type CC1BranchSwitchedPayload,
  CC1BranchSwitchedPayloadSchema,
  type CC1Channel,
  type CC1ConfigIgnoreNestedErrorPayload,
  CC1ConfigIgnoreNestedErrorPayloadSchema,
  type CC1ConfigValidationRejectedPayload,
  CC1ConfigValidationRejectedPayloadSchema,
  type CC1DerivedViewPayload,
  CC1DerivedViewPayloadSchema,
  type CC1DiskAckPayload,
  CC1DiskAckPayloadSchema,
  type CC1ServerInfoPayload,
  CC1ServerInfoPayloadSchema,
  type DerivedViewChannel,
  DerivedViewChannelSchema,
} from './schemas/cc1.ts';
export { isHiddenDocName, isValidDocName, validateDocName } from './util/doc-name.ts';
export { toDesktopAssetHref } from './utils/asset-href.ts';
export { isEmbedUrlRewritable, rewriteEmbedUrl } from './utils/embed-url-rewrite.ts';
export { extensionOf } from './utils/extension.ts';
export { formatFileSize } from './utils/file-size.ts';
export {
  isLoomUrl,
  type ParsedLoomUrl,
  parseLoomUrl,
} from './utils/loom-embed.ts';
export { type PdfAnchorParts, parsePdfAnchor } from './utils/pdf-anchor.ts';
export { isVimeoUrl } from './utils/vimeo-embed.ts';
export {
  type ParsedYouTubeUrl,
  parseYouTubeUrl,
  youtubeEmbedUrl,
} from './utils/youtube-embed.ts';



export {
  applyFastDiff,
  applyIncrementalDiff,
  applyPatchToFm,
  applyPathDeleteToFm,
  applyPathRenameToFm,
  applyPathReorderSeqToFm,
  applyPathReorderToFm,
  applyPathSetToFm,
  applyRenameToFm,
  applyReorderToFm,
  assertContentPreservation,
  BRIDGE_TOLERANCE_CLASSES,
  type BridgeInvariantLogPayload,
  type BridgeInvariantSite,
  type BridgeInvariantViolation,
  BridgeInvariantViolationError,
  BridgeMergeContentLossError,
  type BridgeMergeContentLossInfo,
  type BridgeMergeContentLossLogPayload,
  type BridgeMergeContentLossSide,
  type BridgeMergeContentLossWhich,
  type BridgeToleranceClass,
  bindFrontmatterDoc,
  classifySeverity,
  type DiffChange,
  type DocBoundarySplit,
  defaultScheduler,
  detectAppliedToleranceClasses,
  detectFmRegion,
  diffLinesFast,
  emitToleranceFire,
  type FmEditError,
  type FmEditResult,
  FORM_WRITE_ORIGIN,
  type FrontmatterBinding,
  type FrontmatterBindingPatchResult,
  type FrontmatterBindingPatchSuccess,
  type FrontmatterBindingPathResult,
  type FrontmatterBindingPathSuccess,
  type FrontmatterBindingRenameResult,
  type FrontmatterBindingRenameSuccess,
  type FrontmatterBindingReorderResult,
  type FrontmatterBindingReorderSuccess,
  type FrontmatterBindingUnsubscribe,
  type FrontmatterDocProvider,
  type FrontmatterSnapshot,
  findFirstDivergenceIndex,
  fnv1aDigest,
  type InvariantViolation,
  MAX_FM_REGION_BYTES,
  mergeThreeWay,
  normalizeBridge,
  type ParsedFmRegion,
  parseFencedFmRegion,
  parseFmRegion,
  projectMergeBoundarySpace,
  readFmKeys,
  readFmMap,
  readFmRegionWithError,
  reattachLeadingDocBoundary,
  type Scheduler,
  setToleranceTelemetryHook,
  splitLeadingDocBoundary,
  type ToleranceClassSeverity,
  type ToleranceFireRecord,
  type ToleranceTelemetryHook,
  toBridgeInvariantLog,
} from './bridge/index.ts';
export {
  DEFAULT_SIGTERM_GRACE_MS,
  DEFAULT_SIGTERM_POLL_MS,
  SPAWN_ERROR_LOG,
} from './constants/lifecycle.ts';
export {
  type FrontmatterIssue,
  FrontmatterIssueSchema,
  type FrontmatterValidationError,
  FrontmatterValidationErrorSchema,
  fieldErrorsFromError,
  toFrontmatterIssue,
} from './frontmatter/errors.ts';
export {
  FRONTMATTER_TYPES,
  type FrontmatterMap,
  FrontmatterMapSchema,
  type FrontmatterPatch,
  FrontmatterPatchSchema,
  type FrontmatterType,
  FrontmatterTypeSchema,
  type FrontmatterValue,
  FrontmatterValueSchema,
  frontmatterValuesEqual,
  inferType,
  isFrontmatterValueEmpty,
  isIsoDateString,
  RESERVED_FRONTMATTER_KEY,
} from './frontmatter/schema.ts';
export {
  extractFrontmatterTags,
  FRONTMATTER_TAG_GRAMMAR_HINT,
  FRONTMATTER_TAG_VALUE_RE,
  isValidFrontmatterTagValue,
} from './frontmatter/tags.ts';
export {
  applyPatchToDocument,
  getDocumentKeys,
  type ParsedFrontmatter,
  parseFrontmatterYaml,
  serializeFrontmatterMap,
  withFences,
} from './frontmatter/yaml-codec.ts';
export {
  createWorkspaceSearchCorpus,
  createWorkspaceSearchDocument,
  DEFAULT_RRF_K,
  DEFAULT_VECTOR_CANDIDATE_LIMIT,
  DEFAULT_VECTOR_SIMILARITY_FLOOR,
  DEFAULT_WORKSPACE_SEARCH_LIMIT,
  MAX_WORKSPACE_SEARCH_LIMIT,
  searchWorkspaceCorpus,
  searchWorkspaceDocuments,
  type WorkspaceSearchCorpus,
  type WorkspaceSearchDocument,
  type WorkspaceSearchIntent,
  type WorkspaceSearchKind,
  type WorkspaceSearchOptions,
  type WorkspaceSearchRanking,
  type WorkspaceSearchResult,
  type WorkspaceSearchScope,
  type WorkspaceSemanticInput,
  workspaceSearchBasename,
  workspaceSearchPathSegments,
} from './search/workspace-search.ts';
export {
  type BranchMatchOutcome,
  type Candidate,
  type CandidateBridgeDeps,
  type CandidateSelection,
  type CandidateSelectionPayload,
  canonicalGitHubRemoteUrl,
  classifyBranchMatch,
  type DecodedShare,
  decodeShareUrl,
  type ExpectedShareRepo,
  encodeShareUrl,
  findRecentProjectsForRepo,
  type HeadBranchInfo,
  InvalidShareUrlError,
  type RecentProjectEntry,
  type ResolvedGitDirKind,
  selectCandidate,
  UnsupportedShareVersionError,
} from './sharing/index.ts';
export {
  emptySkillState,
  SKILL_STATE_FILENAME,
  SKILL_STATE_REL,
  SKILL_STATE_SCHEMA_VERSION,
  SKILL_STATE_SURFACES,
  SKILL_STATE_TARGETS,
  SKILL_STATE_VERSION_RE,
  type SkillState,
  SkillStateSchema,
  type SkillStateSurface,
  type SkillStateTarget,
  type SkillStateTargetEntry,
} from './skill-state/schema.ts';
export {
  composeTemplateFile,
  instantiateDoc,
  parseTemplateFile,
  TEMPLATE_IDENTITY_KEY,
  type TemplateIdentity,
  type TemplateModel,
} from './templates/template-format.ts';
export type { Actor, PrincipalId, SessionId } from './types/actor.ts';
export type {
  AgentFlashEntry,
  AgentFocusEntry,
  AgentPresenceEntry,
  AwarenessState,
  AwarenessUser,
} from './types/awareness.ts';
export type { Identity } from './types/identity.ts';
export type { Principal } from './types/principal.ts';
export type {
  EntryType,
  ShadowContributor,
  TimelineEntry,
} from './types/timeline.ts';
export { applyByPrefixSuffix } from './utils/apply-by-prefix-suffix.ts';
export { ChunkedInsertError, chunkedYTextInsert } from './utils/chunked-insert.ts';
export { createCodeFenceTracker } from './utils/code-fence-tracker.ts';
export {
  AGENT_COLORS,
  AGENT_ICON_COLORS,
  AGENT_ICON_COLORS_DARK,
  colorFromSeed,
  computeInitials,
  deriveIconColor,
  displayNameFromClientName,
  formatPresenceLabel,
  generateRandomColor,
  generateRandomName,
  getIdentity,
  HUMAN_COLORS,
  iconFromClientName,
} from './utils/identity.ts';
export {
  type AnchorLinkTarget,
  type AssetLinkTarget,
  assertNeverLinkTarget,
  buildRelativeMarkdownHref,
  type ClassifiedLinkTarget,
  classifyMarkdownHref,
  classifyWikiLinkTarget,
  type DocLinkTarget,
  type ExternalLinkTarget,
  extractAssetExtension,
  isExternalHref,
  resolveAssetProjectPath,
} from './utils/link-targets.ts';
export { type BasenameIndex, createBasenameIndex } from './utils/path-resolve.ts';
export { type ResolvedInternalHref, resolveInternalHref } from './utils/resolve-internal-href.ts';
export { sanitizeFolderName } from './utils/sanitize-folder-name.ts';
export {
  disambiguateSlug,
  getHeadingSlug,
  type HeadingEntry,
  toWikiLinkSlug,
  wikiLinkHref,
} from './utils/slug.ts';
export { expandTagToHierarchy, tagsMatchingPrefix } from './utils/tag-rollup.ts';
